version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lea-postgres
    environment:
      POSTGRES_DB: lea_aesthetics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
